// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukyuiphvvolxhdkaptrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVreXVpcGh2dm9seGhka2FwdHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzUxOTgsImV4cCI6MjA2MTg1MTE5OH0.BTE3Nc2jqaUbKqChWtvy-fqW0aQsK3AftR5H4y4iBzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);